In [4]:
import numpy as np
import pandas as pd
import pymysql

# 데이터 EDA

### 데이터 불러오기

In [5]:
data = pd.read_csv("C:/Users/Songhee/Desktop/AI 부트캠프/Section3/프로젝트/data/서울특별시_전동킥보드_견인현황_20220731/서울특별시_전동킥보드_견인_현황_20220731.csv", encoding='cp949')
data.sample(10)

,번호,신고일,구정보,주소,유형,조치일
43635,43636,2022-04-28,구로구,서울특별시 구로구 구로동 573,기타,2022-04-28
17973,17974,2021-12-10,영등포구,서울특별시 영등포구 대림동 774-2,보도와 차도가 구분된 도로의 차도,2021-12-10
42046,42047,2022-04-19,강서구,서울특별시 강서구 화곡동 1109-1,보도와 차도가 구분된 도로의 차도,2022-04-19
30840,30841,2022-02-21,강동구,서울특별시 강동구 성내동 581,"횡단보도, 산책로 등",2022-02-21
19617,19618,2021-12-21,노원구,서울특별시 노원구 하계동 284,"횡단보도, 산책로 등",2021-12-21
20418,20419,2021-12-27,광진구,서울특별시 광진구 군자동 98,지하철역 진출입로 및 주변,2021-12-27
42105,42106,2022-04-19,강서구,서울특별시 강서구 등촌동 709-24,보도와 차도가 구분된 도로의 차도,2022-04-19
849,850,2021-07-26,송파구,서울특별시 송파구 방이동 94-3,"점자블록, 엘리베이터 입구",2021-07-26
3305,3306,2021-08-20,마포구,서울특별시 마포구 성산동 667,"횡단보도, 산책로 등",2021-08-20
58519,58520,2022-07-19,성동구,서울특별시 성동구 성수동2가 269-25,보도와 차도가 구분된 도로의 차도,2022-07-19

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60605 entries, 0 to 60604
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      60605 non-null  int64
 1   신고일     60605 non-null  object
 2   구정보     60605 non-null  object
 3   주소      60605 non-null  object
 4   유형      60604 non-null  object
 5   조치일     60604 non-null  object
dtypes: int64(1), object(5)
memory usage: 2.8+ MB

In [7]:
data['유형'].unique()

array(['점자블록, 엘리베이터 입구', '보도 중앙', '버스정류장, 택시 승강장', '보도와 차도가 구분된 도로의 차도',
       '기타', '횡단보도, 산책로 등', '건물, 상가 보행자 진출입', '소방시설 5m 이내 구역',
       '육교위, 지하보차도 안', '자전거 도로', '지하철역 진출입로 및 주변', '오신고', '턱을 낮춘 진출입로',
       nan, '통행제한 구간', '계단, 난간'], dtype=object)

In [8]:
len(data['유형'].unique())

16

In [9]:
data[data['신고일'] != data['조치일']]

,번호,신고일,구정보,주소,유형,조치일
9,10,2021-07-15,동작구,서울특별시 동작구 상도동 159-275,기타,2021-07-20
12,13,2021-07-15,동작구,서울특별시 동작구 사당동 1112,기타,2021-07-21
28,29,2021-07-15,동작구,서울특별시 동작구 사당동 1107,기타,2021-07-21
138,139,2021-07-16,동작구,서울특별시 동작구 사당동 1112,기타,2021-07-21
345,346,2021-07-19,동작구,서울특별시 동작구 신대방동 643-1,"횡단보도, 산책로 등",2021-07-20
...,...,...,...,...,...,...
60419,60420,2022-07-28,종로구,서울특별시 종로구 옥인동 24-2,기타,2022-07-29
60420,60421,2022-07-28,종로구,서울특별시 종로구 누하동 94,보도와 차도가 구분된 도로의 차도,2022-07-29
60421,60422,2022-07-28,종로구,서울특별시 종로구 삼청동 35-178,기타,2022-07-29
60422,60423,2022-07-28,중구,서울특별시 중구 을지로1가 63,지하철역 진출입로 및 주변,2022-07-29
60423,60424,2022-07-28,강서구,서울특별시 강서구 가양동 449-27,기타,2022-07-29

### 데이터 전처리

#### 결측치 제거

In [10]:
data.isnull().sum()

번호     0
신고일    0
구정보    0
주소     0
유형     1
조치일    1
dtype: int64

In [11]:
data = data.dropna()

#### 데이터 타입 변경

In [12]:
data['신고일'] = pd.to_datetime(data['신고일'])
data['조치일'] = pd.to_datetime(data['조치일'])

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60604 entries, 0 to 60604
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      60604 non-null  int64
 1   신고일     60604 non-null  datetime64[ns]
 2   구정보     60604 non-null  object
 3   주소      60604 non-null  object
 4   유형      60604 non-null  object
 5   조치일     60604 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 3.2+ MB

#### 특성공학

In [14]:
data['동정보'] = data['주소'].str.split(' ').str[2]

In [15]:
data['상세주소'] = data['주소'].str.split(' ').str[3]

In [16]:
data['조치소요기간'] = data['조치일'] - data['신고일']

In [17]:
data['조치소요기간'] = data['조치소요기간'] / np.timedelta64(1, 'D')
data['조치소요기간']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
60600    0.0
60601    0.0
60602    0.0
60603    0.0
60604    0.0
Name: 조치소요기간, Length: 60604, dtype: float64

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60604 entries, 0 to 60604
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      60604 non-null  int64
 1   신고일     60604 non-null  datetime64[ns]
 2   구정보     60604 non-null  object
 3   주소      60604 non-null  object
 4   유형      60604 non-null  object
 5   조치일     60604 non-null  datetime64[ns]
 6   동정보     60604 non-null  object
 7   상세주소    60552 non-null  object
 8   조치소요기간  60604 non-null  float64
dtypes: datetime64[ns](2), float64(1), int64(1), object(5)
memory usage: 4.6+ MB

In [19]:
data.isnull().sum()

번호         0
신고일        0
구정보        0
주소         0
유형         0
조치일        0
동정보        0
상세주소      52
조치소요기간     0
dtype: int64

In [20]:
data[data['상세주소'].isnull()]

,번호,신고일,구정보,주소,유형,조치일,동정보,상세주소,조치소요기간
598,599,2021-07-22,영등포구,서울특별시 영등포구 영등포동8가,보도와 차도가 구분된 도로의 차도,2021-07-22,영등포동8가,NaN,0.0
2675,2676,2021-08-12,영등포구,서울특별시 영등포구 영등포동8가,"횡단보도, 산책로 등",2021-08-12,영등포동8가,NaN,0.0
3967,3968,2021-08-26,영등포구,서울특별시 영등포구 영등포동6가,"횡단보도, 산책로 등",2021-08-26,영등포동6가,NaN,0.0
5737,5738,2021-09-09,성동구,서울특별시 성동구 용답동,"횡단보도, 산책로 등",2021-09-09,용답동,NaN,0.0
7068,7069,2021-09-17,영등포구,서울특별시 영등포구 신길동,"횡단보도, 산책로 등",2021-09-17,신길동,NaN,0.0
7739,7740,2021-09-27,광진구,서울특별시 광진구 화양동,"버스정류장, 택시 승강장",2021-09-27,화양동,NaN,0.0
9599,9600,2021-10-13,성동구,서울특별시 성동구 홍익동,지하철역 진출입로 및 주변,2021-10-13,홍익동,NaN,0.0
9865,9866,2021-10-14,성동구,서울특별시 성동구 마장동,"횡단보도, 산책로 등",2021-10-14,마장동,NaN,0.0
16984,16985,2021-12-06,동작구,서울특별시 동작구 노량진동,보도와 차도가 구분된 도로의 차도,2021-12-06,노량진동,NaN,0.0
24619,24620,2022-01-18,동대문구,서울특별시 동대문구 답십리동,보도와 차도가 구분된 도로의 차도,2022-01-18,답십리동,NaN,0.0
26037,26038,2022-01-25,동작구,서울특별시 동작구 사당동,"횡단보도, 산책로 등",2022-01-25,사당동,NaN,0.0
26038,26039,2022-01-25,동작구,서울특별시 동작구 사당동,기타,2022-01-25,사당동,NaN,0.0
28427,28428,2022-02-09,마포구,서울특별시 마포구 용강동,보도 중앙,2022-02-09,용강동,NaN,0.0
29728,29729,2022-02-15,영등포구,서울특별시 영등포구 영등포동8가,"점자블록, 엘리베이터 입구",2022-02-15,영등포동8가,NaN,0.0
33221,33222,2022-03-03,성동구,서울특별시 성동구 행당동,"횡단보도, 산책로 등",2022-03-03,행당동,NaN,0.0
33638,33639,2022-03-07,동대문구,서울특별시 동대문구 장안동,오신고,2022-03-07,장안동,NaN,0.0
37028,37029,2022-03-21,마포구,서울특별시 마포구 아현동,"점자블록, 엘리베이터 입구",2022-03-21,아현동,NaN,0.0
37478,37479,2022-03-22,영등포구,서울특별시 영등포구 신길동,"점자블록, 엘리베이터 입구",2022-03-22,신길동,NaN,0.0
37738,37739,2022-03-24,성동구,서울특별시 성동구 행당동,"횡단보도, 산책로 등",2022-03-24,행당동,NaN,0.0
39484,39485,2022-04-05,성동구,서울특별시 성동구 행당동,보도와 차도가 구분된 도로의 차도,2022-04-05,행당동,NaN,0.0
40217,40218,2022-04-08,강남구,서울특별시 강남구 역삼동,보도와 차도가 구분된 도로의 차도,2022-04-08,역삼동,NaN,0.0
41296,41297,2022-04-13,도봉구,서울특별시 도봉구 창동,보도와 차도가 구분된 도로의 차도,2022-04-13,창동,NaN,0.0
41908,41909,2022-04-18,중구,서울특별시 중구 삼각동,보도와 차도가 구분된 도로의 차도,2022-04-18,삼각동,NaN,0.0
44065,44066,2022-05-02,영등포구,서울특별시 영등포구 신길동,보도와 차도가 구분된 도로의 차도,2022-05-02,신길동,NaN,0.0
44700,44701,2022-05-04,성동구,서울특별시 성동구 행당동,보도와 차도가 구분된 도로의 차도,2022-05-04,행당동,NaN,0.0
44717,44718,2022-05-04,영등포구,서울특별시 영등포구 영등포동8가,보도와 차도가 구분된 도로의 차도,2022-05-04,영등포동8가,NaN,0.0
44732,44733,2022-05-06,성동구,서울특별시 성동구 행당동,보도와 차도가 구분된 도로의 차도,2022-05-06,행당동,NaN,0.0
44737,44738,2022-05-06,성동구,서울특별시 성동구 행당동,보도와 차도가 구분된 도로의 차도,2022-05-06,행당동,NaN,0.0
45487,45488,2022-05-10,영등포구,서울특별시 영등포구 신길동,보도와 차도가 구분된 도로의 차도,2022-05-10,신길동,NaN,0.0
45590,45591,2022-05-10,성동구,서울특별시 성동구 행당동,보도와 차도가 구분된 도로의 차도,2022-05-10,행당동,NaN,0.0
46101,46102,2022-05-12,성동구,서울특별시 성동구 행당동,자전거 도로,2022-05-12,행당동,NaN,0.0
46670,46671,2022-05-16,성동구,서울특별시 성동구 행당동,보도와 차도가 구분된 도로의 차도,2022-05-16,행당동,NaN,0.0
46671,46672,2022-05-16,성동구,서울특별시 성동구 행당동,보도와 차도가 구분된 도로의 차도,2022-05-16,행당동,NaN,0.0
46682,46683,2022-05-17,성동구,서울특별시 성동구 행당동,보도와 차도가 구분된 도로의 차도,2022-05-17,행당동,NaN,0.0
46717,46718,2022-05-17,성북구,서울특별시 성북구 보문동6가,보도와 차도가 구분된 도로의 차도,2022-05-17,보문동6가,NaN,0.0
46841,46842,2022-05-17,성동구,서울특별시 성동구 행당동,보도와 차도가 구분된 도로의 차도,2022-05-17,행당동,NaN,0.0
46844,46845,2022-05-17,성동구,서울특별시 성동구 행당동,보도와 차도가 구분된 도로의 차도,2022-05-17,행당동,NaN,0.0
46923,46924,2022-05-18,성동구,서울특별시 성동구 행당동,자전거 도로,2022-05-18,행당동,NaN,0.0
47016,47017,2022-05-18,성동구,서울특별시 성동구 행당동,보도와 차도가 구분된 도로의 차도,2022-05-18,행당동,NaN,0.0
51003,51004,2022-06-09,성북구,서울특별시 성북구 보문동6가,보도와 차도가 구분된 도로의 차도,2022-06-09,보문동6가,NaN,0.0
54374,54375,2022-06-27,관악구,서울특별시 관악구 봉천동,보도와 차도가 구분된 도로의 차도,2022-06-27,봉천동,NaN,0.0
54383,54384,2022-06-27,관악구,서울특별시 관악구 봉천동,보도와 차도가 구분된 도로의 차도,2022-06-27,봉천동,NaN,0.0
54912,54913,2022-07-01,관악구,서울특별시 관악구 봉천동,보도와 차도가 구분된 도로의 차도,2022-07-01,봉천동,NaN,0.0
55687,55688,2022-07-05,종로구,서울특별시 종로구 창덕궁3길20,"계단, 난간",2022-07-05,창덕궁3길20,NaN,0.0
57226,57227,2022-07-12,강남구,서울특별시 강남구 대치동,자전거 도로,2022-07-12,대치동,NaN,0.0
57270,57271,2022-07-12,종로구,서울특별시 종로구 무악동,보도와 차도가 구분된 도로의 차도,2022-07-12,무악동,NaN,0.0
57514,57515,2022-07-14,관악구,서울특별시 관악구 봉천동,보도와 차도가 구분된 도로의 차도,2022-07-14,봉천동,NaN,0.0
59618,59619,2022-07-25,성동구,서울특별시 성동구 성수동1가,보도와 차도가 구분된 도로의 차도,2022-07-25,성수동1가,NaN,0.0
59866,59867,2022-07-26,성동구,서울특별시 성동구 성수동1가,보도와 차도가 구분된 도로의 차도,2022-07-26,성수동1가,NaN,0.0
59995,59996,2022-07-27,성동구,서울특별시 성동구 성수동1가,보도와 차도가 구분된 도로의 차도,2022-07-27,성수동1가,NaN,0.0
60218,60219,2022-07-28,성동구,서울특별시 성동구 성수동1가,보도와 차도가 구분된 도로의 차도,2022-07-28,성수동1가,NaN,0.0
60532,60533,2022-07-29,성동구,서울특별시 성동구 홍익동,보도와 차도가 구분된 도로의 차도,2022-07-29,홍익동,NaN,0.0

In [21]:
data = data.astype({'조치소요기간':'int'})

#### db 저장할 데이터프레임

In [22]:
df_db = data[['번호','신고일','조치일','구정보','동정보','상세주소','유형','조치소요기간']]

In [23]:
df_db.head()

   번호        신고일        조치일  구정보   동정보    상세주소                  유형  조치소요기간
0   1 2021-07-15 2021-07-15  동작구   상도동  215-45      점자블록, 엘리베이터 입구       0
1   2 2021-07-15 2021-07-15  동작구   상도동  172-28               보도 중앙       0
2   3 2021-07-15 2021-07-15  동작구   대방동   356-2       버스정류장, 택시 승강장       0
3   4 2021-07-15 2021-07-15  동작구   대방동   354-1       버스정류장, 택시 승강장       0
4   5 2021-07-15 2021-07-15  동작구  신대방동  460-30  보도와 차도가 구분된 도로의 차도       0

In [24]:
df_db = df_db.where(pd.notnull(df_db), None)

## SQLlite 데이터 적재하기

In [2]:
import sqlite3

In [25]:
conn = sqlite3.connect("C:/Users/Songhee/bootcamp/Section3/Section3_project/kick_board.db")
cur = conn.cursor()

sql = '''INSERT INTO towing (
id, report_date, action_date, gu, dong, detailed_address, category, action_period)
VALUES(?,?,?,?,?,?,?,?)'''

for index, row in df_db.iterrows():
    report_date = row['신고일']
    print(report_date)
    val = (row['번호'],row['신고일'],row['조치일'],row['구정보'],row['동정보'],row['상세주소'],row['유형'],row['조치소요기간'])
    cur.execute(sql, val)
    print(index)

connection.commit() 

cur.close()
conn.close()

2021-07-15 00:00:00

InterfaceError: Error binding parameter 1 - probably unsupported type.

#### 모델링에 사용할 데이터프레임

In [26]:
df = data[['신고일','구정보','동정보','유형','조치소요기간']]

In [27]:
df.head()

         신고일  구정보   동정보                  유형  조치소요기간
0 2021-07-15  동작구   상도동      점자블록, 엘리베이터 입구       0
1 2021-07-15  동작구   상도동               보도 중앙       0
2 2021-07-15  동작구   대방동       버스정류장, 택시 승강장       0
3 2021-07-15  동작구   대방동       버스정류장, 택시 승강장       0
4 2021-07-15  동작구  신대방동  보도와 차도가 구분된 도로의 차도       0

In [28]:
df['신고일']

0       2021-07-15
1       2021-07-15
2       2021-07-15
3       2021-07-15
4       2021-07-15
           ...
60600   2022-07-29
60601   2022-07-29
60602   2022-07-29
60603   2022-07-29
60604   2022-07-29
Name: 신고일, Length: 60604, dtype: datetime64[ns]

# 모델링

In [35]:
df_model.to_csv('save.csv')

In [31]:
df_model = df.copy()

In [32]:
df_model['신고일'] = pd.to_numeric(df_model['신고일'])

In [33]:
from sklearn.model_selection import train_test_split

target = df_model['조치소요기간']
data = df_model.drop(['조치소요기간'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2)

print(f'X_train: {X_train.shape}, y_train: {y_train.shape}')
print(f'X_test: {X_test.shape}, y_test: {y_test.shape}')

X_train: (48483, 4), y_train: (48483,)
X_test: (12121, 4), y_test: (12121,)

In [34]:
!pip install category_encoders

Requirement already satisfied: category_encoders in c:\users\songhee\anaconda3\lib\site-packages (2.5.0)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\songhee\anaconda3\lib\site-packages (from category_encoders) (0.24.2)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\songhee\anaconda3\lib\site-packages (from category_encoders) (0.12.2)
Requirement already satisfied: numpy>=1.14.0 in c:\users\songhee\anaconda3\lib\site-packages (from category_encoders) (1.20.3)
Requirement already satisfied: pandas>=1.0.5 in c:\users\songhee\anaconda3\lib\site-packages (from category_encoders) (1.3.4)
Requirement already satisfied: scipy>=1.0.0 in c:\users\songhee\anaconda3\lib\site-packages (from category_encoders) (1.7.1)
Requirement already satisfied: patsy>=0.5.1 in c:\users\songhee\anaconda3\lib\site-packages (from category_encoders) (0.5.2)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\songhee\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\songhee\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2021.3)
Requirement already satisfied: six in c:\users\songhee\anaconda3\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=0.11 in c:\users\songhee\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\songhee\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (2.2.0)

In [163]:
from category_encoders import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import make_pipeline

In [164]:
pipe_ord = make_pipeline(
    OneHotEncoder(), 
    RandomForestClassifier(random_state=10, n_jobs=-1, oob_score=True)
)

pipe_ord.fit(X_train, y_train)
print('검증 정확도', pipe_ord.score(X_test, y_test))

검증 정확도 0.9970299480240904

In [30]:
test_data = pd.DataFrame(data = [[df_model.iloc[100][0],df_model.iloc[100][1], df_model.iloc[100][2], df_model.iloc[100][3], df_model.iloc[100][4]]], columns=data.columns)

In [81]:
[[df_model.iloc[0]]]

Unnamed: 0                      0
신고일           1626307200000000000
구정보                           동작구
동정보                           상도동
상세주소                       215-45
유형                 점자블록, 엘리베이터 입구
조치소요기간                          0
Name: 0, dtype: object

In [33]:
df_db['유형'].unique()

array(['점자블록, 엘리베이터 입구', '보도 중앙', '버스정류장, 택시 승강장', '보도와 차도가 구분된 도로의 차도',
       '기타', '횡단보도, 산책로 등', '건물, 상가 보행자 진출입', '소방시설 5m 이내 구역',
       '육교위, 지하보차도 안', '자전거 도로', '지하철역 진출입로 및 주변', '오신고', '턱을 낮춘 진출입로',
       '통행제한 구간', '계단, 난간'], dtype=object)

In [186]:
pipe_ord.predict(test_data)

array([0])

In [187]:
import pickle

with open('model.pkl','wb') as pickle_file:
    pickle.dump(pipe_ord, pickle_file)

In [86]:
report_date = '2021-07-28'

In [36]:
from datetime import datetime

In [38]:
date_time_obj = datetime.strptime(report_date, '%Y-%m-%d')

In [67]:
report_date = pd.to_datetime(report_date)

# report_date = pd.to_numeric(report_date)
type(report_date)

pandas._libs.tslibs.timestamps.Timestamp

In [77]:
df_model = pd.read_csv("C:/Users/Songhee/bootcamp/Section3/Section3_project/save.csv")
data = df_model.drop(['Unnamed: 0','조치소요기간'], axis=1)
data

                       신고일  구정보   동정보      상세주소                  유형
0      1626307200000000000  동작구   상도동    215-45      점자블록, 엘리베이터 입구
1      1626307200000000000  동작구   상도동    172-28               보도 중앙
2      1626307200000000000  동작구   대방동     356-2       버스정류장, 택시 승강장
3      1626307200000000000  동작구   대방동     354-1       버스정류장, 택시 승강장
4      1626307200000000000  동작구  신대방동    460-30  보도와 차도가 구분된 도로의 차도
...                    ...  ...   ...       ...                 ...
60599  1659052800000000000  동작구   사당동  708-1025  보도와 차도가 구분된 도로의 차도
60600  1659052800000000000  관악구   봉천동   1693-55  보도와 차도가 구분된 도로의 차도
60601  1659052800000000000  동작구   사당동    175-56  보도와 차도가 구분된 도로의 차도
60602  1659052800000000000  동작구   사당동    175-26  보도와 차도가 구분된 도로의 차도
60603  1659052800000000000  중랑구   면목동    197-10  보도와 차도가 구분된 도로의 차도

[60604 rows x 5 columns]

In [97]:
df_model = pd.read_csv("C:/Users/Songhee/bootcamp/Section3/Section3_project/save.csv")
data = df_model.drop(['Unnamed: 0','조치소요기간'], axis=1)

test_data = pd.DataFrame(data = [[data.iloc[100][0],data.iloc[100][1], data.iloc[100][2], data.iloc[100][3], data.iloc[100][4]]], columns=data.columns)
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   신고일     1 non-null      int64
 1   구정보     1 non-null      object
 2   동정보     1 non-null      object
 3   상세주소    1 non-null      object
 4   유형      1 non-null      object
dtypes: int64(1), object(4)
memory usage: 168.0+ bytes

### pickle 파일 저장

In [83]:
import pickle

model = None
with open('C:/Users/Songhee/bootcamp/Section3/Section3_project/flask_app/models/model.pkl','rb') as pickle_file:
   model = pickle.load(pickle_file)

In [112]:
df_model = pd.read_csv("C:/Users/Songhee/bootcamp/Section3/Section3_project/save.csv")
data = df_model.drop(['Unnamed: 0','조치소요기간'], axis=1)

test_data = pd.DataFrame(data = [[timestamp, gu, dong, detail_address, category]], columns=['신고일','구정보','동정보', '상세주소', '유형'])

In [113]:
test_data

          신고일  구정보  동정보 상세주소     유형
0  1627430400  종로구  평창동   64  보도 중앙